name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  links:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --root-dir ./dist --exclude 'https://docs.odio.love/*' --exclude 'https://pipewire.org/*' --exclude 'https://gnudb.org/*' --exclude-path ./dist/404.html --accept 200,403,418 --insecure ./dist
          fail: true

  spelling:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npx cspell "src/content/docs/**/*.{md,mdx}"
